### ISSUE TITLE
Package error

### ISSUE THREAD

**Issue by Anulo2** [dimensional-de/napi-canon-cameras#21]
npm run package

......
......
> node ./helpers/update-stubs.js && eslint ./src/stubs --fix

mypath\node_modules\node-gyp-build\index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=win32 arch=x64 runtime=node abi=115 uv=1 libc=glibc node=20.6.1
    loaded from: mypath

    at load.path (mypath\node_modules\node-gyp-build\index.js:60:9)
    at load (mypath\node_modules\node-gyp-build\index.js:22:30)
    at Object.<anonymous> (mypath\camera-api.js:1:40)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (mypath\helpers\update-stubs.js:3:13)

Node.js v20.6.1

This might be releted to me using SDK 131810 instead of 131800, can you confirm it's just a matter of using the right SDK version?

**Comment by ahdja** [comment]
me too.. have same error

**Comment by Anulo2** [comment]
Fixed by using 22.0.0 and installing the c++ dev things for visual studio
